### ISSUE TITLE
Continuing to see exceptions in prod against BMO

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#13]
I'm going to assume that our behavior might be triggering this behavior or it's a timing thing where there is additional load.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 294, in connect
    self._tunnel()
  File "/usr/lib64/python3.6/http/client.py", line 919, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 503 Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bugzilla.mozilla.org', port=443): Max retries exceeded with url: /rest/bug/1456277/comment?api_key=**** (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./assigner.py", line 220, in <module>
    main()
  File "./assigner.py", line 66, in main
    autocasa(bapi, capi, bcfg, ccfg, args.dry_run)
  File "./assigner.py", line 93, in autocasa
    comments = bapi.get_comments(bug.get('id'))['bugs'][str(bug.get('id'))]['comments']
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 55, in get_comments
    return self._get('bug/{bugid}/comment'.format(bugid=bugid))
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 120, in _get
    headers=headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bugzilla.mozilla.org', port=443): Max retries exceeded with url: /rest/bug/1456277/comment?api_key=**** (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))
Build step 'Execute shell' marked build as failure

**Comment by claudijd** [comment]
Failure times...

Mon, May 21, 2018 at 1:18 PM
Fri, May 11, 2018 at 8:00 PM
Sun, May 13, 2018 at 3:41 AM
Tue, Apr 10, 2018 at 11:20 AM
Tue, Apr 10, 2018 at 9:00 AM

**Comment by dylanwh** [comment]
this is quite possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=1461819

**Comment by dylanwh** [comment]
(which I'm working on)

**Comment by gdestuynder** [comment]
havent seen these ina  while and we both handle errors + above bug is solved
since theres nothing we can do or observe right now im closing this, but do reopen if you think its necessary or see more errors
