### ISSUE TITLE
Stack trace in assigner script

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#19]
This stack trace happened today, recording so we can improve exception handling in the future...

[RRA and VA auto-assigner] $ /bin/bash -e /tmp/jenkins7708202850648615314.sh
[15:30:30] INFO [__main__.autoassign:213] No unassigned bugs for component
Traceback (most recent call last):
  File "./assigner.py", line 220, in <module>
    main()
  File "./assigner.py", line 65, in main
    autoassign(bapi, bcfg.get('va'), args.dry_run)
  File "./assigner.py", line 182, in autoassign
    bugs = bapi.search_bugs(terms)['bugs']
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 49, in search_bugs
    return DotDict(self._get('bug', params=params))
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 121, in _get
    ret = DotDict(r.json())
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Build step 'Execute shell' marked build as failure

**Comment by gdestuynder** [comment]
note that this is when bugzilla doesnt serve JSON for some reason
