### ISSUE TITLE
RRA Assigner is stacktracing...

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#25]
[20:52:43] WARNING [__main__.autocasa:136] Project REDACTED already has a security status set (done), skipping!

Traceback (most recent call last):
  File "./assigner.py", line 271, in <module>
    main()
  File "./assigner.py", line 267, in main
    autocasa(bapi, capi, config['bugzilla'], config['casa'], args.dry_run)
  File "./assigner.py", line 157, in autocasa
    elif (delegator_id != casa_status['decidingApprover']['id']):
TypeError: 'NoneType' object is not subscriptable
Build step 'Execute shell' marked build as failure

**Comment by gdestuynder** [comment]
thats because the delegator is not in casa

**Comment by gdestuynder** [comment]
@claudijd that means smacleod needs to be added to the right group in casa if im right

**Comment by gdestuynder** [comment]
fixed by https://github.com/mozilla/infosec-risk-management-bugzilla/pull/29
