### ISSUE TITLE
CASA job is failing and spamming folks

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#41]
I have disable the CASA sync job because it's stack tracing and spamming us...

Here's the stack trace...

[17:06:43] DEBUG [__main__.main:303] Selected modules to run: ['casa']
Traceback (most recent call last):
  File "./assigner.py", line 314, in <module>
    main()
  File "./assigner.py", line 310, in main
    autocasa(bapi, capi, config['bugzilla'], config['casa'], args.dry_run)
  File "./assigner.py", line 112, in autocasa
    bugs = bapi.search_bugs(terms)['bugs']
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 49, in search_bugs
    return DotDict(self._get('bug', params=params))
  File "/usr/lib/python3.6/site-packages/bugzilla.py", line 121, in _get
    ret = DotDict(r.json())
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Build step 'Execute shell' marked build as failure
Sending e-mails to: jclaudius@mozilla.com gdestuynder@mozilla.com culucenk@mozilla.com
Finished: FAILURE

**Comment by floatingatoll** [comment]
That’s interesting, is CASA or Bugzilla the site returning 0-byte invalid
JSON responses?

**Comment by gdestuynder** [comment]
nevermind after further investigation, bugzilla is throttling our requests

**Comment by gdestuynder** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1501370

**Comment by gdestuynder** [comment]
Fixed, see bug for info. I re enabled the job
