### ISSUE TITLE
TypeError: ‘NoneType’ object is not iterable "/home/jenkins/jenkins-agent/jenkins-agent/workspace/CASA Assigner/casa.py", line 124, in casa_set_status

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#55]
Affected line:    decisionLabel, decision = decision_map.get(bug_resolution)

**Comment by claudijd** [comment]
This is due to setting a "WORKSFORME" status, which doesn't exist in the map.  I'm going to change  the status of the offending bug and see if we can restore it's function.

**Comment by claudijd** [comment]
Example stack trace:

Traceback (most recent call last):
  File "./assigner.py", line 314, in <module>
    main()
  File "./assigner.py", line 310, in main
    autocasa(bapi, capi, config['bugzilla'], config['casa'], args.dry_run)
  File "./assigner.py", line 211, in autocasa
    res = capi.casa_set_status(project_id, delegator_id, bug.get('resolution'))
  File "/home/jenkins/jenkins-agent/jenkins-agent/workspace/CASA Assigner/casa.py", line 124, in casa_set_status
    decisionLabel, decision = decision_map.get(bug_resolution)
TypeError: 'NoneType' object is not iterable

**Comment by claudijd** [comment]
The work around for now is simply not to  use that status.  The fix here would be just to have it bail or provide an additional mapping for the "WORKSFORME" and any other possible outcomes.
